name: shell commands

on: [push, pull]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "PoshBaba!"
      - name: multiline script 
        run: |
          node -v 
          npm -v 